//
// Created by level-128 on 1/19/24.
//

#ifndef INCL_BKLIBKEY
#define INCL_BKLIBKEY

#include <errno.h>
#include <float.h>
#include <wchar.h>
#ifdef CFG_ASCII
#include "../libsrc/ucar.c"
#else
#include <uchar.h>
#endif

#include "bksrclib.c"
#include "../libsrc/auxlib.c"
#include "../include/windham_const.h"
#include "../include/huffman.h"
#include "../include/sha256.h"

#define MIN_KEY_CHAR 7


typedef struct {
   char *   key_or_keyfile_location;
   uint32_t key_type;
   size_t   key_data_len;  // length for char32_t pre-hashed key
} Key;


enum {
   NMOBJ_key_file_type_input,
   // ask key
   NMOBJ_key_file_type_input_systemd,
   // ask key through systemd
   NMOBJ_key_file_type_input_stdin,
   // key from stdin
   NMOBJ_key_file_type_key,
   // using --key
   NMOBJ_key_file_type_file,
   // keyfile
   NMOBJ_key_file_type_masterkey,
   // --master-key=
   NMOBJ_key_file_type_key_raw,
   // random key generated by windham
   NMOBJ_key_file_type_key_char32_t_str,
   // pre-hashed char32_t password (used by LINK_OPEN cascade)
};


#define MAX_PASSWORD_INPUT_LEN 256


uint8_t hex_char_to_int(char ch) {
   if (ch == 0) {
      print_error(_("error when parsing key: invalid length"));
   }
   if ('0' <= ch && ch <= '9') {
      return ch - '0';
   }
   if ('a' <= ch && ch <= 'f') {
      return ch - 'a' + 10;
   }
   print_error(_("error when parsing key: invalid character; only hexadecimal is accepted."));
   return -1;
}


bool master_key_to_byte_array(const char * hex_string, uint8_t byte_array[HASHLEN]) {
   int str_index = 0, byte_index = 0;
   while (byte_index != HASHLEN) {
      while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
         ++str_index;
      }

      int high_nibble = hex_char_to_int(hex_string[str_index]);
      ++str_index;
      while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
         ++str_index;
      }

      int low_nibble = hex_char_to_int(hex_string[str_index]);

      byte_array[byte_index] = (high_nibble << 4) + low_nibble;
      str_index ++;
      ++byte_index;
   }
   while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
      ++str_index;
   }
   if (hex_string[str_index] != 0) {
      return false;
   }
   return true;
}

static void password_to_sha256(const char32_t *password, unsigned char_count, uint8_t out[HASHLEN]) {
   SHA256_CTX ctx;
   sha256_init(&ctx);

   for (unsigned i = 0; i < char_count; i++) {
      char32_t ch = password[i];
      uint8_t be[4] = {
         (uint8_t)((ch >> 24) & 0xFF),
         (uint8_t)((ch >> 16) & 0xFF),
         (uint8_t)((ch >> 8) & 0xFF),
         (uint8_t)(ch & 0xFF)
      };
      sha256_update(&ctx, be, 4);
   }

   sha256_final(&ctx, out);
}


unsigned get_key_input_from_the_console(const char *device, char32_t password[MAX_PASSWORD_INPUT_LEN], const bool is_new_key) {
   printf(_("Password for %s:\n"), device);
   bool is_unicode_input = false;
   unsigned count = get_password_input(password, &is_unicode_input);
   if (is_new_key == true && !is_unicode_input) {
      char32_t password2[MAX_PASSWORD_INPUT_LEN];
      printf(_("\nConfirm password:\n"));
      bool dummy_unicode;
      unsigned count2 = get_password_input(password2, &dummy_unicode);
      if (count != count2) {
         print_error(_("Passwords do not match."));
      }
      for (unsigned i = 0; i < count; i++) {
         if (password[i] != password2[i]) {
            print_error(_("Passwords do not match."));
         }
      }
      if (count < MIN_KEY_CHAR) {
         print_error(
            _("the provided password is too short (%u characters), which is not recommended. To bypass this restriction, use "
               "argument --key instead."),
            count);
      }
   }
   return count;
}





void read_key_file(const Key key, uint8_t inited_key[HASHLEN]) {
   const char *filename = key.key_or_keyfile_location;
   uint8_t *fdata;

   FILE *fp = fopen(filename, "rb");
   if (fp == NULL) {
      print_error(_("Cannot open keyfile %s. Reason: %s"), filename, strerror(errno));
   }

   if (fseek(fp, 0, SEEK_END) != 0) {
      print_error(_("Cannot seek keyfile %s: %s"), filename, strerror(errno));
   }
   long fsize = ftell(fp);
   if (fsize < 0) {
      print_error(_("Cannot determine size of keyfile %s: %s"), filename, strerror(errno));
   }
   rewind(fp);

   fdata = malloc(fsize);
   if (fread(fdata, 1, fsize, fp) != (size_t)fsize) {
      print_error(_("Error reading keyfile %s"), filename);
   }
   fclose(fp);

   unsigned ccount = (fsize + 3) / 4;
   char32_t *pw = malloc(ccount * sizeof(char32_t));
   for (unsigned i = 0; i < ccount; i++) {
      char32_t val = 0;
      unsigned base = i * 4;
      if (base < (unsigned)fsize)       val |= (char32_t)fdata[base] << 24;
      if (base + 1 < (unsigned)fsize)   val |= (char32_t)fdata[base + 1] << 16;
      if (base + 2 < (unsigned)fsize)   val |= (char32_t)fdata[base + 2] << 8;
      if (base + 3 < (unsigned)fsize)   val |= (char32_t)fdata[base + 3];
      pw[i] = val;
   }
   free(fdata);
   password_to_sha256(pw, ccount, inited_key);
   free(pw);
}


void read_key_stdin(uint8_t inited_key[HASHLEN]) {
#ifdef WINDHAM_PLAT_GNU_LINUX
   char buffer[4096];
   ssize_t n = read(STDIN_FILENO, buffer, sizeof(buffer) - 1);
   if (n <= 0) {
      print_error(_("Failed to read from stdin for --keystdin: %s"), strerror(errno));
   }
   buffer[n] = '\0';

   while (n > 0 && (buffer[n-1] == '\n' || buffer[n-1] == '\r'))
      buffer[--n] = '\0';

   unsigned out_len = 0;
   char32_t *pw = convert_key_to_unicode(buffer, &out_len);
   password_to_sha256(pw, out_len, inited_key);
   free(pw);
#else
   print_error(_("--keystdin is not available under ISO C."));
#endif
}


bool prepare_key(const Key key, uint8_t inited_key[HASHLEN], const char *device, bool is_new_key) {
   unsigned char_count = 0;
   char32_t password[MAX_PASSWORD_INPUT_LEN];
   char32_t *heap_password = NULL;

   switch (key.key_type) {
   case NMOBJ_key_file_type_masterkey:
      return false;
    case NMOBJ_key_file_type_input:
       char_count = get_key_input_from_the_console(device, password, is_new_key);
       password_to_sha256(password, char_count, inited_key);
       break;
    case NMOBJ_key_file_type_input_systemd:
       char_count = get_key_input_from_the_console_systemd(device, password);
       password_to_sha256(password, char_count, inited_key);
       break;
   case NMOBJ_key_file_type_file:
      read_key_file(key, inited_key);
      return true;
    case NMOBJ_key_file_type_key: {
       unsigned out_len = 0;
       heap_password = convert_key_to_unicode(key.key_or_keyfile_location, &out_len);
       char_count = out_len;
       password_to_sha256(heap_password, char_count, inited_key);
       break;
    }
   case NMOBJ_key_file_type_input_stdin:
      read_key_stdin(inited_key);
      break;
    case NMOBJ_key_file_type_key_raw:
       memcpy(inited_key, key.key_or_keyfile_location, HASHLEN);
       return true;
    case NMOBJ_key_file_type_key_char32_t_str: {
       char32_t *pw = (char32_t *)key.key_or_keyfile_location;
       password_to_sha256(pw, (unsigned)key.key_data_len, inited_key);
       char_count = (unsigned)key.key_data_len;
       heap_password = pw;
       break;
    }
    default:
      exit(2);
   }

   const char32_t *pw = heap_password ? heap_password : password;
   bool result;
   if (char_count == 0) {
      result = false;
   } else if ((size_t)char_count * 4 > 1024) {
      result = true;
   } else {
      uint8_t be_bytes[MAX_PASSWORD_INPUT_LEN * 4];
      for (unsigned i = 0; i < char_count; i++) {
         char32_t ch = pw[i];
         be_bytes[i * 4 + 0] = (uint8_t)((ch >> 24) & 0xFF);
         be_bytes[i * 4 + 1] = (uint8_t)((ch >> 16) & 0xFF);
         be_bytes[i * 4 + 2] = (uint8_t)((ch >> 8) & 0xFF);
         be_bytes[i * 4 + 3] = (uint8_t)(ch & 0xFF);
      }
      result = get_is_high_entropy(char_count * 4, be_bytes);
   }

   free(heap_password);
   return result;
}


char * interactive_ask_new_key_test_key = NULL;


void action_addkey_interactive_prepare_key(Key * new_key) {
   int option = 1;
   if (interactive_ask_new_key_test_key == NULL) {
      option = ask_option("Add a new key: choose your key format.", "input key from console", "use a key file", NULL);
   }
   if (option == 1) {
      if (interactive_ask_new_key_test_key == NULL) {
         new_key->key_type                = NMOBJ_key_file_type_input;
         new_key->key_or_keyfile_location = NULL;
      } else {
         new_key->key_type                = NMOBJ_key_file_type_key;
         new_key->key_or_keyfile_location = interactive_ask_new_key_test_key;
         interactive_ask_new_key_test_key = NULL;
      }
   } else if (option == 2) {
      char file_location[FILENAME_MAX + 1];
      size_t len             = 0;
      printf("Key file location:");
      if (fgets(file_location, sizeof(file_location), stdin) != NULL) {
         len = strlen(file_location);
         if (len == FILENAME_MAX && file_location[FILENAME_MAX - 1] != '\n') {
            print_error(_("Input file location too long."));
         }
         if (len == 1) {
            print_error(_("input file location is empty."));
         }
         file_location[len - 1] = '\0';

      } else {
         print_error(_("Error file name input."));
      }
      // we know len, use memcpy which is faster than strdup, plus strdup is optional.
      char * file_location_str = malloc(len);
      memcpy(file_location_str, file_location, len);
      new_key->key_or_keyfile_location = file_location_str;
      new_key->key_type                = NMOBJ_key_file_type_file;
   }
}


void get_master_key(
   Data         self,
   uint8_t      master_key[HASHLEN],
   const Key    key,
   const char * device,
   uint64_t     max_unlock_mem,
   double       max_unlock_time,
   int          max_unlock_level,
   const bool   is_allow_nolock,
   unsigned *   ret_level,
   unsigned *   ret_key_zone,
   uint16_t *   ret_key_location,
   uint8_t      ret_inited_key[HASHLEN]) {
   if (key.key_type == NMOBJ_key_file_type_masterkey) { // do nothing
      if (check_master_key_check(self, master_key) == false) {
         print_error(_("Wrong master key."));
      }
      memset(ret_inited_key, 0, HASHLEN);
      return;
   }
   uint8_t inited_key[HASHLEN];
   prepare_key(key, inited_key, device, false);
   memcpy(ret_inited_key, inited_key, HASHLEN);

   *ret_key_location = get_keypool_location_candidate(self.master_key_mask, inited_key);

   max_unlock_mem = check_target_mem(max_unlock_mem, false, is_allow_nolock);

   Key_slot keyslots[2];
   memcpy(&keyslots[0], &self.keypool[0].keypool[*ret_key_location], sizeof(Key_slot));
   memcpy(&keyslots[1], &self.keypool[1].keypool[*ret_key_location], sizeof(Key_slot));

   int unlocked_slot = read_key_from_data(
      self,
      inited_key,
      *ret_key_location,
      max_unlock_time,
      max_unlock_mem,
      max_unlock_level,
      is_allow_nolock,
      ret_key_zone,
      ret_level,
      master_key);

   switch (unlocked_slot){
      case NMOBJ_Enclib_alloc_failed_no_free_mem:
      print_error(
         _("Cannot unlock the target because of insufficient system memory.\n"
            "\tIf you are certain that the key is indeed correct, try consider exporting the master key on a more "
            "computationally powerful device and then use the master key to unlock the target."));

      case NMOBJ_Enclib_alloc_failed_policy_nolock:
      print_error(
         _("Cannot unlock the target because of insufficient system memory.\n"
            "\tIf you are certain that the key is indeed correct, try enable swap using --allow-swap. DO NOT ENABLE "
            "THIS OPTION IF THE SWAP SPACE STORES AS PLAINTEXT ON NON-VOLATILE DEVICE!"));

      case NMOBJ_Enclib_calc_failed_no_time:
      print_error(
         _("Cannot unlock the target probably due to incorrect key.\n"
            "\tIf you are certain that the key is indeed correct, because the time limit has reached, try increasing the maximum "
            "time limit "
            "using --max-unlock-time."));

      case NMOBJ_Enclib_calc_failed_level_exceeded:
      print_error(
         _("Cannot unlock the target because unlock level has been reached. Double check your "
           "parameters or key."));

      case NMOBJ_Enclib_calc_failed_reached_max_mem:
      print_error(
         _("Cannot unlock the target because max memory has been reached. Double check your "
           "parameters or key."));

      case NMOBJ_Enclib_alloc_failed_lock_error:
      print_error(
         _("Cannot unlock the target because windham tries to lock memory into physical RAM but failed "
           "while --allow-swap is not given. Use \"ulimit -m\" to increase mem-lock size for this process."));

      }


}


void print_msg_for_generate_key_slot(
   int      return_val,
   uint64_t target_mem) {
   switch (return_val) {
   case NMOBJ_Enclib_alloc_failed_no_free_mem:
      if (target_mem) {
         print_warning(_("Designated memory constrains cannot be reached due to insufficient system ram."));
      } else {
         print_warning(_("The system has no enough free ram to met its security target. "));
      }
      break;
   case NMOBJ_Enclib_alloc_failed_policy_nolock:
      print_warning(_("Designated memory constrains cannot be reached due to insufficient system ram."));
      break;
   case NMOBJ_Enclib_alloc_failed_lock_error:
      print_error(_("Failed to lock memory: hitting resource limit (RLIMIT_MEMLOCK) or missing CAP_IPC_LOCK permission."));
      break;
   default: ;
   }
}

void add_key_to_keyslot(
   Data *        decrypted_self,
   const uint8_t master_key[HASHLEN],
   const Key     key_key,
   const char *  device,
   uint64_t      target_mem,
   const double  target_time,
   const int     target_level,
   const bool    is_no_detect_entropy,
   const bool    rapid_add,
   const bool    is_anonymous_key,
   const bool    is_allow_nolock,
   int *         ret_target_level) {
#define SET_BIT(n, x, y) ((n & ~(1ULL << (x))) | (((uint64_t)(y) & 1) << (x)))

   uint8_t inited_key[HASHLEN];

   int free_slot;
   // check slot availability
   for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
      if (decrypted_self->metadata.keyslot_level[i] == 0) {
         free_slot = i;
         goto END_LOOP;
      }
   }
   print_error(_("No free slot available. Remove a password or keyfile to free a slot."));
END_LOOP:;

   // prepare key and print message for high entropy key.
   const bool is_high_entropy_key = prepare_key(key_key, inited_key, device, true);
   if (is_high_entropy_key) {
      if (key_key.key_type == NMOBJ_key_file_type_file) {
         printf(
            _(
               "Using a key file allows you to add keys to key slots with decreased cost to increase unlock speed. "
               "to disable this feature, use \"--no-detect-entropy\"\n"));
      } else if (key_key.key_type != NMOBJ_key_file_type_input_stdin && key_key.key_type !=
                 NMOBJ_key_file_type_key_raw) {
         // EMOBJ_key_file_type_input_stdin has is_high_entropy_key attribute true
         printf(
            _(
               "High entropy passphrase detected, adding the passphrase to the keyslot with decreased cost to increase unlock "
               "speed. to disable this feature, use \"--no-detect-entropy\"\n"));
      }
   }

   // detect is already registered.
   for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
      if (memcmp(decrypted_self->metadata.keyslot_key[i], inited_key, HASHLEN) == 0) {
         print_error(_("The given key is used at slot %i"), i);
      }
   }

    // get new key mem and time
    if (is_high_entropy_key && ! is_no_detect_entropy) {
       // Allow exactly one KDF pass at level 0, then stop after level 0
       target_mem = kdf_mem_bounds[1][1];
    } else if (target_level != KEY_SLOT_EXP_MAX) {
      // target_level will overwrite everything. in this case, target_mem does not count
      target_mem = check_target_mem(target_mem, true, is_allow_nolock);
   }

   // rapid add tries to add the key to the slot without changing master_key_mask.
   // check key offset in slot, and place to the keyslot if possible.
   if (rapid_add) {
      Key_slot key_slot;
      int      keyslot_level;

      fill_secure_random_bits((uint8_t *) &key_slot, sizeof(key_slot));

      int return_val = generate_key_slot_key_mask(
         *decrypted_self,
         inited_key,
         master_key,
         target_time,
         target_mem,
         target_level,
         is_allow_nolock,
         &keyslot_level,
         &key_slot);
      print_msg_for_generate_key_slot(return_val, target_mem);

      uint16_t keypool_location_candidate = get_keypool_location_candidate(decrypted_self->master_key_mask, inited_key);
      int      index                      = get_possible_key_location_in_keypool(
         decrypted_self->metadata,
         keypool_location_candidate,
         keyslot_level);
      if (index == -1) {
         print_error(
            _(
               "Rapid Add cannot locate a free area within keypool that could satisfies all constrains. This might happen with a very low "
               "probability, because Rapid Add does not guarantee to add a new password (as it does so incrementally), especially if the partition already has a "
               "lot of passwords registered. Please omit --rapid-add or select a new password if possible."));
      }

      // place key_slot to keypool
      memcpy(
         &decrypted_self->keypool[index].keypool[keypool_location_candidate],
         &key_slot,
         convert_stage_to_size(keyslot_level));
      if (is_anonymous_key == false) {
         memcpy(decrypted_self->metadata.keyslot_key[free_slot], inited_key, HASHLEN);
      } else {
         memset(decrypted_self->metadata.keyslot_key[free_slot], 0, HASHLEN);
      }
      decrypted_self->metadata.keyslot_location_area = SET_BIT(
         decrypted_self->metadata.keyslot_location_area,
         free_slot,
         index);
      decrypted_self->metadata.keyslot_level[free_slot]    = keyslot_level;
      decrypted_self->metadata.keyslot_location[free_slot] = keypool_location_candidate;

      *ret_target_level = keyslot_level;
   } else {
      // non-rapid add.
      // 1. remove all Anonymous keys
      // 2. reassign master_key_mask
      // 3. calculate new key
      Key_slot key_slots[KEY_SLOT_COUNT];
      uint8_t  keyslot_levels[KEY_SLOT_COUNT];

      memcpy(keyslot_levels, decrypted_self->metadata.keyslot_level, KEY_SLOT_COUNT);

      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0 && memcmp(
                decrypted_self->metadata.keyslot_key[i],
                (uint8_t[HASHLEN]){0},
                HASHLEN) == 0) {
            ask_for_conformation(
               _(
                  "Anonymous key registered at slot %i. Non rapid add does not support transforming anonymous key, thus "
                  "this key will be dropped and invalidated. Proceed?"),
               i);
            keyslot_levels[i] = 0;
         }
      }

      fill_secure_random_bits(decrypted_self->master_key_mask, HASHLEN);
      fill_secure_random_bits((uint8_t *) key_slots, sizeof(key_slots));
      // fill all slots to hide side channel information.

      // calculate new key
      int keyslot_level;
      int return_val = generate_key_slot_key_mask(
         *decrypted_self,
         inited_key,
         master_key,
         target_time,
         target_mem,
         target_level,
         is_allow_nolock,
         &keyslot_level,
         &key_slots[free_slot]);
      print_msg_for_generate_key_slot(return_val, target_mem);

      keyslot_levels[free_slot] = keyslot_level;
      memcpy(decrypted_self->metadata.keyslot_key[free_slot], inited_key, HASHLEN);
      *ret_target_level = keyslot_level;

      bool is_failed_attempt = false;


   GET_RANDOM_LOC_FAILED:
      if (is_failed_attempt) {
         fill_secure_random_bits(decrypted_self->master_key_mask, HASHLEN);
         fill_secure_random_bits((uint8_t *) key_slots, sizeof(key_slots));
         // fill all slots to hide side channel information.
      }
      memset(decrypted_self->metadata.keyslot_level, 0, sizeof(decrypted_self->metadata.keyslot_level));
      memset(decrypted_self->metadata.keyslot_location, 0, sizeof(decrypted_self->metadata.keyslot_location));


      // find possible slot displacement
      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0) {
            decrypted_self->metadata.keyslot_location[i] = get_keypool_location_candidate(
               decrypted_self->
               master_key_mask,
               decrypted_self->metadata.
                               keyslot_key[i]);
            int index = get_possible_key_location_in_keypool(
               decrypted_self->metadata,
               decrypted_self->metadata.keyslot_location[i],
               keyslot_levels[i]);
            if (index == -1) {
               is_failed_attempt = true;
               goto GET_RANDOM_LOC_FAILED;
            } else {
               decrypted_self->metadata.keyslot_level[i]      = keyslot_levels[i];
               decrypted_self->metadata.keyslot_location_area = SET_BIT(
                  decrypted_self->metadata.keyslot_location_area,
                  i,
                  index);
            }
         }
      }

      // calculate all old keys. if failed attempt occurs, then calculate new keys within this loop.
      int  keyslot_level_loop;
      bool is_level_okey = true;
      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (i != free_slot || is_failed_attempt) {
            if (keyslot_levels[i] != 0) {
               return_val = generate_key_slot_key_mask(
                  *decrypted_self,
                  decrypted_self->metadata.keyslot_key[i],
                  master_key,
                  DBL_MAX,
                  SIZE_MAX,
                  keyslot_levels[i],
                  is_allow_nolock,
                  &keyslot_level_loop,
                  &key_slots[i]);
               if (return_val != NMOBJ_Enclib_gen_okay_level_reached) {
                  is_level_okey = false;
                  print_warning(
                     _("Cannot met target strength for key %i, target iteration level: %"PRIu16", iteration done: %i"),
                     i,
                     keyslot_levels[i],
                     keyslot_level_loop);
                  keyslot_levels[i] = keyslot_level_loop;
               }
            }
         }
      }
      if (! is_level_okey) {
         ask_for_conformation(
            _(
               "when transforming passwords, some of them cannot reach their original iteration level. "
               "A powerful device, which is able to perform more key iterations, will provides enhanced protection against weak passwords. "
               "This warning is probably because the local"
               " machine has much less memory than the device which add those passwords, or Windham is not "
               "configured to utilise swap space and memory is currently in scarce. Are you willing to proceed?"));
      }
      set_master_key_check(decrypted_self, master_key);

      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0) {
            memcpy(
               &decrypted_self->keypool[
                  GET_BIT(decrypted_self->metadata.keyslot_location_area, i)
               ].keypool[
                  decrypted_self->metadata.keyslot_location[i]
               ],
               &key_slots[i],
               convert_stage_to_size(keyslot_levels[i]));
         }
      }
   }
}

#endif
