//
// Created by level-128 on 1/19/24.
//

#pragma once

#include <errno.h>
#include <float.h>
#include <wchar.h>

#include "bksrclib.c"
#include "../include/windham_const.h"
#include "../include/huffman.h"
#include "../include/sha256.h"

#define MIN_KEY_CHAR 7


typedef struct {
   char *   key_or_keyfile_location;
   uint32_t key_type;
} Key;


enum {
   NMOBJ_key_file_type_input,
   // ask key
   NMOBJ_key_file_type_input_systemd,
   // ask key through systemd
   NMOBJ_key_file_type_input_stdin,
   // key from stdin
   NMOBJ_key_file_type_key,
   // using --key
   NMOBJ_key_file_type_file,
   // keyfile
   NMOBJ_key_file_type_masterkey,
   // --master-key=
   NMOBJ_key_file_type_key_raw,
   // random key generated by windham
};


#define MAX_PASSWORD_INPUT_LEN 256


uint8_t hex_char_to_int(char ch) {
   if (ch == 0) {
      print_error(_("error when parsing key: invalid length"));
   }
   if ('0' <= ch && ch <= '9') {
      return ch - '0';
   }
   if ('a' <= ch && ch <= 'f') {
      return ch - 'a' + 10;
   }
   print_error(_("error when parsing key: invalid character; only hexadecimal is accepted."));
   return -1;
}


bool master_key_to_byte_array(const char * hex_string, uint8_t byte_array[HASHLEN]) {
   int str_index = 0, byte_index = 0;
   while (byte_index != HASHLEN) {
      while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
         ++str_index;
      }

      int high_nibble = hex_char_to_int(hex_string[str_index]);
      ++str_index;
      while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
         ++str_index;
      }

      int low_nibble = hex_char_to_int(hex_string[str_index]);

      byte_array[byte_index] = (high_nibble << 4) + low_nibble;
      str_index ++;
      ++byte_index;
   }
   while (hex_string[str_index] == ' ' || hex_string[str_index] == '-' || hex_string[str_index] == '\n') {
      ++str_index;
   }
   if (hex_string[str_index] != 0) {
      return false;
   }
   return true;
}

int wcwidth(wchar_t c);

int get_char_display_width(const char * mbchar) {
   // This function is possible only under POSIX context.
#ifndef WINDHAM_ISOC
   wchar_t wch;

   int len = mbtowc(&wch, mbchar, MB_CUR_MAX);
   if (len <= 0) {
      return 0; // Invalid multibyte character or conversion error
   }

   // Get the display width of the wide character
   int width = wcwidth(wch);
   if (width < 0) {
      return 0; // Non-printable character
   }

   return width;
#else
   return 1;
#endif
}

int bklibkey_check_hex(int ch) {
   if (ch >= 'A' && ch <= 'F') {
      return ch - 'A' + 10;
   }
   if (ch >= '0' && ch <= '9') {
      return ch - '0';
   }
   if (ch >= 'a' && ch <= 'f') {
      return ch - 'a' + 10;
   }
   return -1;
}

void get_password_input(char input[MAX_PASSWORD_INPUT_LEN]) {
   // no frontend entry does not modify terminal mode.
#if defined(IS_FRONTEND_ENTRY) && !defined(WINDHAM_ISOC)
   struct termios raw = oldt;
   raw.c_lflag &= ~(ICANON | ECHO);
   tcsetattr(STDIN_FILENO, TCSANOW, &raw);
#endif
   bool is_echo = false;
   bool is_raw  = false;

   static_assert(UINT_FAST16_MAX > MAX_PASSWORD_INPUT_LEN, "max password len is too large");

   for (uint_fast16_t index = 0; index + 1 < MAX_PASSWORD_INPUT_LEN; index ++) {
      int ch = getchar();

      if (is_raw) {
         if (ch == '\n') {
            if (index == 0) {
               print_error(
                  _("Empty input. Password required, input password as 2 hexadecimal lower "
                     "case characters."));
            }
            input[index] = '\00';
            goto END;
         }
         if (ch == '\x7f') {
            index -= 2;
            printf("\b\b\b   \b\b\b");
            continue;
         }
         int ch_num = bklibkey_check_hex(ch);
         if (ch_num == -1) {
            putchar(7);
            index --;
            continue;
         }
         putchar(ch);

         const int ch2     = getchar();
         int       ch2_num = bklibkey_check_hex(ch2);
         if (ch2_num == -1) {
            printf("\b \b");
            putchar(7);
            index --;
            continue;
         }
         putchar(ch2);

         if (ch_num == 0 && ch2_num == 0) {
            printf("\b\b  \b\b");
            putchar(7);
            index --;
            continue;
         }
         input[index] = (ch_num << 4) + ch2_num;
         putchar(' ');
         continue;
      }

      if (ch == '\n') {
         if (index == 0) {
            print_error(_("Empty input. Password required."));
         }
         input[index] = '\00';
         goto END;
      }

      if (ch == '\t') {
         if (is_echo == true) {
            putchar(7);
            index --;
            continue;
         }
         char * msg;
         if (index == 0) {
            msg = _("press tab to echo; press space for hex mode");
         } else {
            msg = _("press tab to echo");
         }

         printf("%s", msg);
         fflush(stdout);
         ch = getchar();

         printf("\r");
         for (unsigned i = 0; i < strlen(msg); i ++) {
            printf(" ");
         }
         printf("\r");
         fflush(stdout);

         if (ch == '\t') {
            input[index] = '\x00';
            printf("%s", input);
            fflush(stdout);
            is_echo = true;
         }
         if (ch == ' ' && index == 0) {
            printf(_("Hex mode: enter 2 hexadecimal lower case characters to represent a byte. 0x00 is not allowed.\n"));
            is_raw = true;
         }
         index --;
         continue;
      }

      if (ch == '\x7f') {
         if (index == 0) {
            putchar(7);
            index --;
            continue;
         }
         // delete multibyte for utf-8
         for (int i = 0; index - i != 1 && input[index - i - 1] >= '\x80' && input[index - i - 1] <= '\xbf'; i ++) {
            index --;
         }

         printf("\b \b");
         index --;
         input[index] = 0;
         index --;
         continue;
      }

      if (is_echo) {
         putchar(ch);
      }

      input[index] = ch;
   }
   printf("\n");
   print_warning(
      _("The max password input size is %i bytes. No new input will be accepted. Consider key file instead."
      ),
      MAX_PASSWORD_INPUT_LEN - 1);
   printf(_("press enter to proceed."));
   while (getchar() != '\n') { }
   input[MAX_PASSWORD_INPUT_LEN - 1] = '\00';

END:
#if defined(IS_FRONTEND_ENTRY) && !defined(WINDHAM_ISOC)

   tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
#endif

   if (strcmp(input, "level-128") == 0) {
      print_error("👿");
   }
}


void get_key_input_from_the_console(const char * device, char password[MAX_PASSWORD_INPUT_LEN], const bool is_new_key) {
   printf(_("Password for %s:\n"), device);
   get_password_input(password);
   if (is_new_key == true) {
      char password2[MAX_PASSWORD_INPUT_LEN];
      printf(_("\nConfirm password:\n"));
      get_password_input(password2);
      if (strcmp(password, password2) != 0) {
         print_error(_("Passwords do not match."));
      }
      if (strlen(password) < MIN_KEY_CHAR) {
         print_error(
            _("the provided password is too short (%zu characters), which is not recommended. To bypass this restriction, use "
               "argument --key instead."),
            strlen(password));
      }
   }

   if (is_new_key) { }
}


void get_key_input_from_the_console_systemd(const char * device, char password[MAX_PASSWORD_INPUT_LEN]) {
#ifndef WINDHAM_ISOC
   int    exec_ret_val;
   char * dup_stdout = NULL;
   char * exec_dir[] = {"/bin", "/usr/bin", "/sbin", "/usr/sbin", NULL};
   size_t dup_stdout_len;
   char   password_prompt[strlen("password for ") + strlen(device) + strlen(":") + 1];
   sprintf(password_prompt, "password for %s:", device);

   if (exec_name(
          "systemd-ask-password",
          exec_dir,
          -1,
          &dup_stdout,
          &dup_stdout_len,
          &exec_ret_val,
          NMOBJ_exec_name_wait_child,
          password_prompt,
          NULL) == false) {
      if (errno == ENOENT) {
         print_error(
            _(
               "\"systemd-ask-password\" is not available. Param \"--systemd-dialog\" only supports system with systemd as init."
            ));
      } else {
         print_error(_("failed to call \"systemd-ask-password\"."));
      }
   } else if (exec_ret_val != 0) {
      print_error(_("Cannot get password from systemd service"));
   }
   dup_stdout[dup_stdout_len - 1] = '\x00';
   strncpy(password, dup_stdout, MAX_PASSWORD_INPUT_LEN);
   free(dup_stdout);
#else
   exit(2);
#endif
}


void read_key_file(const Key key, uint8_t inited_key[HASHLEN]) {
   const char *filename = key.key_or_keyfile_location;
   uint8_t buffer[1024];
   SHA256_CTX sha_256_ctx;
   size_t bytes_read;

   FILE *fp = fopen(filename, "rb");
   if (fp == NULL) {
      print_error(_("Cannot open keyfile %s. Reason: %s"), filename, strerror(errno));
   }

   sha256_init(&sha_256_ctx);

   while ((bytes_read = fread(buffer, 1, sizeof(buffer), fp))) {
       sha256_update(&sha_256_ctx, buffer, bytes_read);
   }

   // exit due to error
   if (ferror(fp)) {
       print_error(_("Error reading keyfile %s: %s"), filename, strerror(errno));
       fclose(fp);
       return;
   }

   sha256_final(&sha_256_ctx, inited_key);
   fclose(fp);
}


void read_key_stdin(uint8_t inited_key[HASHLEN]) {
#ifndef WINDHAM_ISOC
   char buffer[1024];

   int fd = open("/dev/stdin", O_RDONLY);
   if (fd == -1) {
      perror("open");
      windham_exit(1);
   }

   ssize_t bytes_read = read(fd, buffer, sizeof(buffer) - 1);
   if (bytes_read == -1) {
      perror("read");
      windham_exit(1);
   }
   if (bytes_read == sizeof(buffer)) {
      print_error(_("input is too long!"));
   }
   buffer[bytes_read] = '\0';
   close(fd);
   if (master_key_to_byte_array(buffer, inited_key) == false) {
      print_error(_("error when parsing key: invalid length"));
   }
#else
print_error(_("--keystdin is not available under ISO C."))
#endif
}


bool prepare_key(const Key key, uint8_t inited_key[HASHLEN], const char * device, bool is_new_key) {
   size_t key_size = 0;
   char   password[MAX_PASSWORD_INPUT_LEN];

   switch (key.key_type) {
   case NMOBJ_key_file_type_masterkey:
      return false;
   case NMOBJ_key_file_type_input:
      get_key_input_from_the_console(device, password, is_new_key);
      key_size = strlen(password);
      sha256_digest_all(password, key_size, inited_key);
      break;
   case NMOBJ_key_file_type_input_systemd:
      get_key_input_from_the_console_systemd(device, password);
      key_size = strlen(password);
      sha256_digest_all(password, key_size, inited_key);
      break;
   case NMOBJ_key_file_type_file:
      read_key_file(key, inited_key);
      return true;
   case NMOBJ_key_file_type_key:
      key_size = strlen(key.key_or_keyfile_location);
      sha256_digest_all(key.key_or_keyfile_location, key_size, inited_key);
      break;
   case NMOBJ_key_file_type_input_stdin:
      read_key_stdin(inited_key);
      return true; // the key has high entropy
   case NMOBJ_key_file_type_key_raw:
      memcpy(inited_key, key.key_or_keyfile_location, HASHLEN);
      return true;
   default:
      exit(2);
   }
   const bool result = get_is_high_entropy(key_size, (uint8_t *) password);
   return result;
}


char * interactive_ask_new_key_test_key = NULL;


void action_addkey_interactive_prepare_key(Key * new_key) {
   int option = 1;
   if (interactive_ask_new_key_test_key == NULL) {
      option = ask_option("Add a new key: choose your key format.", "input key from console", "use a key file", NULL);
   }
   if (option == 1) {
      if (interactive_ask_new_key_test_key == NULL) {
         new_key->key_type                = NMOBJ_key_file_type_input;
         new_key->key_or_keyfile_location = NULL;
      } else {
         new_key->key_type                = NMOBJ_key_file_type_key;
         new_key->key_or_keyfile_location = interactive_ask_new_key_test_key;
         interactive_ask_new_key_test_key = NULL;
      }
   } else if (option == 2) {
      char file_location[FILENAME_MAX + 1];
      size_t len             = 0;
      printf("Key file location:");
      if (fgets(file_location, sizeof(file_location), stdin) != NULL) {
         len = strlen(file_location);
         if (len == FILENAME_MAX && file_location[FILENAME_MAX - 1] != '\n') {
            print_error(_("Input file location too long."));
         }
         if (len == 1) {
            print_error(_("input file location is empty."));
         }
         file_location[len - 1] = '\0';

      } else {
         print_error(_("Error file name input."));
      }
      // we know len, use memcpy which is faster than strdup, plus strdup is optional.
      char * file_location_str = malloc(len);
      memcpy(file_location_str, file_location, len);
      new_key->key_or_keyfile_location = file_location_str;
      new_key->key_type                = NMOBJ_key_file_type_file;
   }
}


void get_master_key(
   Data         self,
   uint8_t      master_key[HASHLEN],
   const Key    key,
   const char * device,
   uint64_t     max_unlock_mem,
   double       max_unlock_time,
   int          max_unlock_level,
   const bool   is_allow_nolock,
   unsigned *   ret_level,
   unsigned *   ret_key_zone,
   uint16_t *   ret_key_location) {
   if (key.key_type == NMOBJ_key_file_type_masterkey) { // do nothing
      if (check_master_key_check(self, master_key) == false) {
         print_error(_("Wrong master key."));
      }
      return;
   }
   uint8_t inited_key[HASHLEN];
   prepare_key(key, inited_key, device, false);

   *ret_key_location = get_keypool_location_candidate(self.master_key_mask, inited_key);

   max_unlock_mem = check_target_mem(max_unlock_mem, false, is_allow_nolock);

   Key_slot keyslots[2];
   memcpy(&keyslots[0], &self.keypool[0].keypool[*ret_key_location], sizeof(Key_slot));
   memcpy(&keyslots[1], &self.keypool[1].keypool[*ret_key_location], sizeof(Key_slot));

   int unlocked_slot = read_key_from_data(
      self,
      inited_key,
      *ret_key_location,
      max_unlock_time,
      max_unlock_mem,
      max_unlock_level,
      is_allow_nolock,
      ret_key_zone,
      ret_level,
      master_key);

   switch (unlocked_slot){
      case NMOBJ_Enclib_alloc_failed_no_free_mem:
      print_error(
         _("Cannot unlock the target because of insufficient system memory.\n"
            "\tIf you are certain that the key is indeed correct, try consider exporting the master key on a more "
            "computationally powerful device and then use the master key to unlock the target."));

      case NMOBJ_Enclib_alloc_failed_policy_nolock:
      print_error(
         _("Cannot unlock the target because of insufficient system memory.\n"
            "\tIf you are certain that the key is indeed correct, try enable swap using --allow-swap. DO NOT ENABLE "
            "THIS OPTION IF THE SWAP SPACE STORES AS PLAINTEXT ON NON-VOLATILE DEVICE!"));

      case NMOBJ_Enclib_calc_failed_no_time:
      print_error(
         _("Cannot unlock the target probably due to incorrect key.\n"
            "\tIf you are certain that the key is indeed correct, because the time limit has reached, try increasing the maximum "
            "time limit "
            "using --max-unlock-time."));

      case NMOBJ_Enclib_calc_failed_level_exceeded:
      print_error(
         _("Cannot unlock the target because unlock level has been reached. Double check your "
           "parameters or key."));

      case NMOBJ_Enclib_calc_failed_reached_max_mem:
      print_error(
         _("Cannot unlock the target because max memory has been reached. Double check your "
           "parameters or key."));

      case NMOBJ_Enclib_alloc_failed_lock_error:
      print_error(
         _("Cannot unlock the target because windham tries to lock memory into physical RAM but failed "
           "while --allow-swap is not given. Use \"ulimit -m\" to increase mem-lock size for this process."));

      }


}


void print_msg_for_generate_key_slot(
   int      return_val,
   uint64_t target_mem) {
   switch (return_val) {
   case NMOBJ_Enclib_alloc_failed_no_free_mem:
      if (target_mem) {
         print_warning(_("Designated memory constrains cannot be reached due to insufficient system ram."));
      } else {
         print_warning(_("The system has no enough free ram to met its security target. "));
      }
      break;
   case NMOBJ_Enclib_alloc_failed_policy_nolock:
      print_warning(_("Designated memory constrains cannot be reached due to insufficient system ram."));
      break;
   case NMOBJ_Enclib_alloc_failed_lock_error:
      print_error(_("Failed to lock memory: hitting resource limit (RLIMIT_MEMLOCK) or missing CAP_IPC_LOCK permission."));
      break;
   default: ;
   }
}

void add_key_to_keyslot(
   Data *        decrypted_self,
   const uint8_t master_key[HASHLEN],
   const Key     key_key,
   const char *  device,
   uint64_t      target_mem,
   const double  target_time,
   const int     target_level,
   const bool    is_no_detect_entropy,
   const bool    rapid_add,
   const bool    is_anonymous_key,
   const bool    is_allow_nolock,
   int *         ret_target_level) {
#define SET_BIT(n, x, y) ((n & ~(1U << (x))) | ((y & 1) << (x)))

   uint8_t inited_key[HASHLEN];

   int free_slot;
   // check slot availability
   for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
      if (decrypted_self->metadata.keyslot_level[i] == 0) {
         free_slot = i;
         goto END_LOOP;
      }
   }
   print_error(_("No free slot available. Remove a password or keyfile to free a slot."));
END_LOOP:;

   // prepare key and print message for high entropy key.
   const bool is_high_entropy_key = prepare_key(key_key, inited_key, device, true);
   if (is_high_entropy_key) {
      if (key_key.key_type == NMOBJ_key_file_type_file) {
         printf(
            _(
               "Using a key file allows you to add keys to key slots with decreased cost to increase unlock speed. "
               "to disable this feature, use \"--no-detect-entropy\"\n"));
      } else if (key_key.key_type != NMOBJ_key_file_type_input_stdin && key_key.key_type !=
                 NMOBJ_key_file_type_key_raw) {
         // EMOBJ_key_file_type_input_stdin has is_high_entropy_key attribute true
         printf(
            _(
               "High entropy passphrase detected, adding the passphrase to the keyslot with decreased cost to increase unlock "
               "speed. to disable this feature, use \"--no-detect-entropy\"\n"));
      }
   }

   // detect is already registered.
   for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
      if (memcmp(decrypted_self->metadata.keyslot_key[i], inited_key, HASHLEN) == 0) {
         print_error(_("The given key is used at slot %i"), i);
      }
   }

   // get new key mem and time
   if (is_high_entropy_key && ! is_no_detect_entropy) {
      target_mem = 0;
   } else if (target_level != KEY_SLOT_EXP_MAX) {
      // target_level will overwrite everything. in this case, target_mem does not count
      target_mem = check_target_mem(target_mem, true, is_allow_nolock);
   }

   // rapid add tries to add the key to the slot without changing master_key_mask.
   // check key offset in slot, and place to the keyslot if possible.
   if (rapid_add) {
      Key_slot key_slot;
      int      keyslot_level;

      fill_secure_random_bits((uint8_t *) &key_slot, sizeof(key_slot));

      int return_val = generate_key_slot_key_mask(
         *decrypted_self,
         inited_key,
         master_key,
         target_time,
         target_mem,
         target_level,
         is_allow_nolock,
         &keyslot_level,
         &key_slot);
      print_msg_for_generate_key_slot(return_val, target_mem);

      uint16_t keypool_location_candidate = get_keypool_location_candidate(decrypted_self->master_key_mask, inited_key);
      int      index                      = get_possible_key_location_in_keypool(
         decrypted_self->metadata,
         keypool_location_candidate,
         keyslot_level);
      if (index == -1) {
         print_error(
            _(
               "Rapid Add cannot locate a free area within keypool that could satisfies all constrains. This might happen with a very low "
               "probability, because Rapid Add does not guarantee to add a new password (as it does so incrementally), especially if the partition already has a "
               "lot of passwords registered. Please omit --rapid-add or select a new password if possible."));
      }

      // place key_slot to keypool
      memcpy(
         &decrypted_self->keypool[index].keypool[keypool_location_candidate],
         &key_slot,
         convert_stage_to_size(keyslot_level));
      if (is_anonymous_key == false) {
         memcpy(decrypted_self->metadata.keyslot_key[free_slot], inited_key, HASHLEN);
      } else {
         memset(decrypted_self->metadata.keyslot_key[free_slot], 0, HASHLEN);
      }
      decrypted_self->metadata.keyslot_location_area = SET_BIT(
         decrypted_self->metadata.keyslot_location_area,
         free_slot,
         index);
      decrypted_self->metadata.keyslot_level[free_slot]    = keyslot_level;
      decrypted_self->metadata.keyslot_location[free_slot] = keypool_location_candidate;

      *ret_target_level = keyslot_level;
   } else {
      // non-rapid add.
      // 1. remove all Anonymous keys
      // 2. reassign master_key_mask
      // 3. calculate new key
      Key_slot key_slots[KEY_SLOT_COUNT];
      uint8_t  keyslot_levels[KEY_SLOT_COUNT];

      memcpy(keyslot_levels, decrypted_self->metadata.keyslot_level, KEY_SLOT_COUNT);

      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0 && memcmp(
                decrypted_self->metadata.keyslot_key[i],
                (uint8_t[HASHLEN]){0},
                HASHLEN) == 0) {
            ask_for_conformation(
               _(
                  "Anonymous key registered at slot %i. Non rapid add does not support transforming anonymous key, thus "
                  "this key will be dropped and invalidated. Proceed?"),
               i);
            keyslot_levels[i] = 0;
         }
      }

      fill_secure_random_bits(decrypted_self->master_key_mask, HASHLEN);
      fill_secure_random_bits((uint8_t *) key_slots, sizeof(key_slots));
      // fill all slots to hide side channel information.

      // calculate new key
      int keyslot_level;
      int return_val = generate_key_slot_key_mask(
         *decrypted_self,
         inited_key,
         master_key,
         target_time,
         target_mem,
         target_level,
         is_allow_nolock,
         &keyslot_level,
         &key_slots[free_slot]);
      print_msg_for_generate_key_slot(return_val, target_mem);

      keyslot_levels[free_slot] = keyslot_level;
      memcpy(decrypted_self->metadata.keyslot_key[free_slot], inited_key, HASHLEN);
      *ret_target_level = keyslot_level;

      bool is_failed_attempt = false;


   GET_RANDOM_LOC_FAILED:
      if (is_failed_attempt) {
         fill_secure_random_bits(decrypted_self->master_key_mask, HASHLEN);
         fill_secure_random_bits((uint8_t *) key_slots, sizeof(key_slots));
         // fill all slots to hide side channel information.
      }
      memset(decrypted_self->metadata.keyslot_level, 0, sizeof(decrypted_self->metadata.keyslot_level));
      memset(decrypted_self->metadata.keyslot_location, 0, sizeof(decrypted_self->metadata.keyslot_location));


      // find possible slot displacement
      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0) {
            decrypted_self->metadata.keyslot_location[i] = get_keypool_location_candidate(
               decrypted_self->
               master_key_mask,
               decrypted_self->metadata.
                               keyslot_key[i]);
            int index = get_possible_key_location_in_keypool(
               decrypted_self->metadata,
               decrypted_self->metadata.keyslot_location[i],
               keyslot_levels[i]);
            if (index == -1) {
               is_failed_attempt = true;
               goto GET_RANDOM_LOC_FAILED;
            } else {
               decrypted_self->metadata.keyslot_level[i]      = keyslot_levels[i];
               decrypted_self->metadata.keyslot_location_area = SET_BIT(
                  decrypted_self->metadata.keyslot_location_area,
                  i,
                  index);
            }
         }
      }

      // calculate all old keys. if failed attempt occurs, then calculate new keys within this loop.
      int  keyslot_level_loop;
      bool is_level_okey = true;
      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (i != free_slot || is_failed_attempt) {
            if (keyslot_levels[i] != 0) {
               return_val = generate_key_slot_key_mask(
                  *decrypted_self,
                  decrypted_self->metadata.keyslot_key[i],
                  master_key,
                  DBL_MAX,
                  SIZE_MAX,
                  keyslot_levels[i],
                  is_allow_nolock,
                  &keyslot_level_loop,
                  &key_slots[i]);
               if (return_val != NMOBJ_Enclib_gen_okay_level_reached) {
                  is_level_okey = false;
                  print_warning(
                     _("Cannot met target strength for key %i, target iteration level: %"PRIu16", iteration done: %i"),
                     i,
                     keyslot_levels[i],
                     keyslot_level_loop);
                  keyslot_levels[i] = keyslot_level_loop;
               }
            }
         }
      }
      if (! is_level_okey) {
         ask_for_conformation(
            _(
               "when transforming passwords, some of them cannot reach their original iteration level. "
               "A powerful device, which is able to perform more key iterations, will provides enhanced protection against weak passwords. "
               "This warning is probably because the local"
               " machine has much less memory than the device which add those passwords, or Windham is not "
               "configured to utilise swap space and memory is currently in scarce. Are you willing to proceed?"));
      }
      set_master_key_check(decrypted_self, master_key);

      for (int i = 0; i < KEY_SLOT_COUNT; i ++) {
         if (keyslot_levels[i] != 0) {
            memcpy(
               &decrypted_self->keypool[
                  GET_BIT(decrypted_self->metadata.keyslot_location_area, i)
               ].keypool[
                  decrypted_self->metadata.keyslot_location[i]
               ],
               &key_slots[i],
               convert_stage_to_size(keyslot_levels[i]));
         }
      }
   }
}
